# Linter for build files
env:
  amd: true
  es6: true
extends:
  - eslint:recommended
  - standard
rules:
  no-console: off
  array-callback-return:
    - error
    - allowImplicit: true
  dot-notation:
    - error
    - allowKeywords: true
  function-paren-newline:
    - error
    - consistent
  max-len:
    - error
    - code: 80
  no-useless-return:
    - error
  no-var:
    - error
  semi:
    - error
    - always
